scripts: adding cryptography to requirements.txt
When installing using GS guide, then users are requested to run:
`pip install --user scripts/requirements.txt`, but if they then tries to
build asset_tracker, they will see following error:
    ModuleNotFoundError: No module named 'cryptography'

The commit adds cryptography as a required python package.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>