workflows: docbuild: Use ubuntu-22.04
This workflow was designed to run on this particular ubuntu version
when publishing NCS 2.6. Now a newer ubuntu version is used
which is incompatible:

```
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: wheel
    Found existing installation: wheel 0.42.0
ERROR: Cannot uninstall wheel 0.42.0, RECORD file not found.
Hint: The package was installed by debian.
```

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>