net: openthread: make CONFIG_OPENTHREAD_NRF_SECURITY_PSA enable Mbed TLS
In some scenarios we would get an undefined reference to
mbedtls_debug_set_threshold() because Mbed TLS wouldn't be compiled in.

The proper fix for this would be to #ifdef out the use of this function
if it is the only undefined reference.

Signed-off-by: Tomi Fontanilles <tomi.fontanilles@nordicsemi.no>