doc: Fix broken build after SUPL msc merge
PR #2009 introduced changes to the SUPL rST file including a msc block.
This is currently breaking the build with:

```
writing output... [ 90%] include/supl_os_client

Exception occurred:
  File "/home/utzig/.pyenv/versions/3.7.4/lib/python3.7/site-packages/sphinxcontrib/mscgen.py", line 171, in render_msc_html
    self.builder.warn('mscgen code %r: ' % code + str(exc))
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'warn'
The full traceback has been saved in /tmp/sphinx-err-qlho2z7s.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[3]: *** [CMakeFiles/nrf-html.dir/build.make:77: CMakeFiles/nrf-html] Error 2
make[2]: *** [CMakeFiles/Makefile2:470: CMakeFiles/nrf-html.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:559: CMakeFiles/nrf.dir/rule] Error 2
make: *** [Makefile:333: nrf] Error 2
```

It seems to be related to a label including a '\n'.

The current setup has sphinx==2.4.4 and sphinxcontrib-mscgen==0.5.

Signed-off-by: Fabio Utzig <fabio.utzig@nordicsemi.no>