scripts: Fix cryptography python package minimum version requirement
Fix cryptography python package minimum version requirement.
scripts/bootloader/keygen.py uses a function in a way that does not
work with older versions, e.g. 2.8.0, where the generate_private_key
has a required 'backend' argument.

Fails with the following message:
key = ec.generate_private_key(ec.SECP256R1())
TypeError: generate_private_key() missing 1 required positional
argument: 'backend'.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>