doc: Fix nrfutil trace version for v2.9.0 nRF54H20 RC1
The documentation tells to install nrfutil trace v3.10.0, but this version
does not seem to exist :
```
:~/ncs$ nrfutil install trace=3.10.0 --force
nrfutil-trace already installed
Uninstalled nrfutil-trace
Error: Failed to install nrfutil-trace

Caused by:
    0: Package index file error
    1: Unable to find version '3.10.0' in the package index file
```

However, the latest version seems to be v3.1.0 :
```
:~/ncs$ nrfutil trace --version
nrfutil-trace 3.1.0 (2da0997 2024-12-11)
commit-hash: 2da0997efbe37ef990d0a0384eb49d13264bab45
commit-date: 2024-12-11
host: x86_64-unknown-linux-gnu
build-timestamp: 2024-12-12T08:08:37.332171808Z
classification: nrf-external
```

Signed-off-by: Adrien Ricciardi <aricciardi@baylibre.com>