modules: memfault: Fix build error for device_info_init
```plaintext
modules/memfault-firmware-sdk/memfault_integration.c:84:12: \
  error: 'device_info_init' declared 'static' but never defined \
  [-Werror=unused-function]
   84 | static int device_info_init(void);
      |            ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

In the case where none of these conditions are met:

```c
#if defined(CONFIG_MEMFAULT_NCS_DEVICE_ID_HW_ID) || \
        defined(CONFIG_MEMFAULT_NCS_DEVICE_ID_IMEI) || \
        defined(CONFIG_MEMFAULT_NCS_DEVICE_ID_NET_MAC)
```

Confirmed that with this fix, building like so completes successfully
(where previously it failed):

```bash
❯ west build --sysbuild --pristine=always \
  --board nrf54l15dk/nrf54l15/cpuapp \
  nrf/samples/bluetooth/peripheral_mds \
  -- \
  -DCONFIG_MEMFAULT_NCS_PROJECT_KEY=\"dummy\" \
  -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y
```

Signed-off-by: Noah Pendleton <noah.pendleton@nordicsemi.no>