scripts: quarantine_llvm: add samples due to spim error
error: label at end of compound statement is a C23 extension

Signed-off-by: Piotr Kosycarz <piotr.kosycarz@nordicsemi.no>