Revert "tests: subsys: esb: Add ESB sample integration test"
This reverts commit f021095c145c845366b2fcad3232595a2e85b6e3.

Gives:
twisterlib.error.TwisterRuntimeError: Duplicated test scenarios found

Signed-off-by: Piotr Kosycarz <piotr.kosycarz@nordicsemi.no>